print("Welcome To Month's Calender")
print("If Month's Get Multiplied by 12, it return the same one.")
print("Please Select The Month To Calculate")
print("1. January")
print("2. February")
print("3. March")
print("4. April")
print("5. May")
print("6. June")
print("7. July")
print("8. August")
print("9. September")
print("10. October")
print("11. November")
print("12. December")
print("What Month Is Today?")
month=input("Please Select The Month By Number: ")

if month=='1':
    print("What Do You Prefer?")
    print("1. Further Month")
    print("2. BackWard Month")
    prefer=input("Please Select Which One Do You Prefer By Number: ")
    if prefer=='1':
        further=input("Wanna Further For How Long Of Month? (1-12): ")